# Generated by Django 4.0.5 on 2022-06-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_secret',
        ),
    ]
