# Generated by Django 4.0.5 on 2022-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
