# Generated by Django 4.0.5 on 2022-07-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_approval',
            field=models.BooleanField(default=False),
        ),
    ]
